config/routes.rb
Rails.application.routes.draw do
  resources :payments
  resources :advances
  resources :operative_plans
  devise_for :users
  get 'welcome/index'

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/advance.rb
class Advance < ApplicationRecord
  belongs_to :operative_plan
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/operative_plan.rb
class OperativePlan < ApplicationRecord
  has_many :advances, dependent: :destroy
end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/advances_controller.rb
class AdvancesController < ApplicationController
  before_action :set_advance, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /advances
  # GET /advances.json
  def index
    @advances = Advance.all
  end

  # GET /advances/1
  # GET /advances/1.json
  def show
  end

  # GET /advances/new
  def new
    @advance = Advance.new
  end

  # GET /advances/1/edit
  def edit
  end

  # POST /advances
  # POST /advances.json
  def create
    @advance = Advance.new(advance_params)

    respond_to do |format|
      if @advance.save
        format.html { redirect_to @advance, notice: 'Avance creado exitosamente' }
        format.json { render :show, status: :created, location: @advance }
      else
        format.html { render :new }
        format.json { render json: @advance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /advances/1
  # PATCH/PUT /advances/1.json
  def update
    respond_to do |format|
      if @advance.update(advance_params)
        format.html { redirect_to @advance, notice: 'Avance actualizado exitosamente' }
        format.json { render :show, status: :ok, location: @advance }
      else
        format.html { render :edit }
        format.json { render json: @advance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /advances/1
  # DELETE /advances/1.json
  def destroy
    @advance.destroy
    respond_to do |format|
      format.html { redirect_to advances_url, notice: 'Avance eliminado exitosamente' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_advance
      @advance = Advance.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def advance_params
      params.require(:advance).permit(:name, :description, :operative_plan_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/operative_plans_controller.rb
class OperativePlansController < ApplicationController
  before_action :set_operative_plan, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /operative_plans
  # GET /operative_plans.json
  def index
    @operative_plans = OperativePlan.all
  end

  # GET /operative_plans/1
  # GET /operative_plans/1.json
  def show
  end

  # GET /operative_plans/new
  def new
    @operative_plan = OperativePlan.new
  end

  # GET /operative_plans/1/edit
  def edit
  end

  # POST /operative_plans
  # POST /operative_plans.json
  def create
    @operative_plan = OperativePlan.new(operative_plan_params)

    respond_to do |format|
      if @operative_plan.save
        format.html { redirect_to @operative_plan, notice: 'Plan operativo creado exitosamente' }
        format.json { render :show, status: :created, location: @operative_plan }
      else
        format.html { render :new }
        format.json { render json: @operative_plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /operative_plans/1
  # PATCH/PUT /operative_plans/1.json
  def update
    respond_to do |format|
      if @operative_plan.update(operative_plan_params)
        format.html { redirect_to @operative_plan, notice: 'Plan operativo actualizado exitosamente' }
        format.json { render :show, status: :ok, location: @operative_plan }
      else
        format.html { render :edit }
        format.json { render json: @operative_plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /operative_plans/1
  # DELETE /operative_plans/1.json
  def destroy
    @operative_plan.destroy
    respond_to do |format|
      format.html { redirect_to operative_plans_url, notice: 'Plan operativo eliminado exitosamente' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_operative_plan
      @operative_plan = OperativePlan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def operative_plan_params
      params.require(:operative_plan).permit(:name, :description)
    end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /payments
  # GET /payments.json
  def index
    @payments = Payment.all
  end

  # GET /payments/1
  # GET /payments/1.json
  def show
  end

  # GET /payments/new
  def new
    @payment = Payment.new
  end

  # GET /payments/1/edit
  def edit
  end

  # POST /payments
  # POST /payments.json
  def create
    @payment = Payment.new(payment_params)

    respond_to do |format|
      if @payment.save
        format.html { redirect_to @payment, notice: 'Payment was successfully created.' }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1
  # PATCH/PUT /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to @payment, notice: 'Payment was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @payment.destroy
    respond_to do |format|
      format.html { redirect_to payments_url, notice: 'Payment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = Payment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_params
      params.require(:payment).permit(:name, :description, :info)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/advances_helper.rb
module AdvancesHelper
  def plans_for_select
    OperativePlan.all.collect { |m| [m.name, m.id] }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def custom_bootstrap_flash
    flash_messages = []
    flash.each do |type, message|
      type = 'success' if type == 'notice'
      type = 'error'   if type == 'alert'
      text = "<script>toastr.#{type}('#{message}');</script>"
      flash_messages << text.html_safe if message
    end
    flash_messages.join("\n").html_safe
  end 
end

app/helpers/operative_plans_helper.rb
module OperativePlansHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/advances/_form.html.haml
= form_for @advance do |f|
  .field
    = f.label :name, 'Nombre'
    = f.text_field :name
  .field
    = f.label :description, 'Descripción'
    = f.text_area :description
  .field
    = f.label :operative_plan_id, 'Plan operativo'
    = f.select(:operative_plan_id, plans_for_select)
  .actions
    = f.submit 'Guardar'

app/views/advances/edit.html.haml
%h1 Editando avance

= render 'form'

= link_to 'Mostrar', @advance
\|
= link_to 'Atrás', advances_path

app/views/advances/index.html.haml
%h1 Mostrando avances

- if current_user.admin?
  = link_to 'Nuevo avance', new_advance_path
  \|
= link_to 'Volver a los planes operativos', operative_plans_path

%table
  %thead
    %tr
      %th Nombre
      %th Descripción
      %th Plan operativo
      %th
      %th
      %th

  %tbody
    - @advances.each do |advance|
      %tr
        %td= advance.name
        %td=raw advance.description
        %td= advance.operative_plan.name
        %td= link_to 'Mostrar', advance
        - if current_user.admin?
          %td= link_to 'Editar', edit_advance_path(advance)
          %td= link_to 'Eliminar', advance, method: :delete, data: { confirm: '¿Estás seguro?' }

%br

app/views/advances/new.html.haml
%h1 Nuevo avance

= render 'form'

= link_to 'Atrás', advances_path

app/views/advances/show.html.haml
%p
  %b Nombre:
  = @advance.name
%p
  %b Plan operativo:
  = @advance.operative_plan.name
%p
  %b Descripción:
  %br
  = raw @advance.description


= link_to 'Editar', edit_advance_path(@advance)
\|
= link_to 'Atrás', advances_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Sarita
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application'
  %body
    = custom_bootstrap_flash
    %nav
      .nav-wrapper.container
        %a.brand-logo{:href=>"/"} Sarita
        %ul#nav-mobile.right.hide-on-med-and-down
          %li=link_to "Inicio", root_path
          - if user_signed_in?
            %li=link_to "Planes operativos", operative_plans_path
            %li=link_to "Pagos", payments_path
            - if current_user.admin?
              %li=link_to "Avances", advances_path
            %li=link_to "Mi cuenta", edit_user_registration_path
            %li=link_to "Cerrar sesión", destroy_user_session_path, method: :delete
          - else
            %li=link_to "Iniciar sesión", new_user_session_path
    .container
      = yield

app/views/operative_plans/_form.html.haml
= form_for @operative_plan do |f|
  .field
    = f.label :name, 'Nombre'
    = f.text_field :name
  .field
    = f.label :description, 'Descripción'
    = f.text_area :description
  .actions
    = f.submit 'Guardar'

app/views/operative_plans/edit.html.haml
%h1 Editando plan operativo

= render 'form'

= link_to 'Mostrar', @operative_plan
\|
= link_to 'Atrás', operative_plans_path

app/views/operative_plans/index.html.haml
%h1 Mostrando planes operativos

- if current_user.admin?
  = link_to 'Nuevo plan operativo', new_operative_plan_path

%table
  %thead
    %tr
      %th Nombre
      %th Descripción
      %th
      %th
      %th

  %tbody
    - @operative_plans.each do |operative_plan|
      %tr
        %td= operative_plan.name
        %td= operative_plan.description
        %td= link_to 'Mostrar', operative_plan
        - if current_user.admin?
          %td= link_to 'Editar', edit_operative_plan_path(operative_plan)
          %td= link_to 'Eliminar', operative_plan, method: :delete, data: { confirm: '¿Estás seguro?' }

%br

app/views/operative_plans/new.html.haml
%h1 Nuevo plan operativo

= render 'form'

= link_to 'Atrás', operative_plans_path

app/views/operative_plans/show.html.haml
%p
  %b Nombre:
  = @operative_plan.name
%p
  %b Descripción:
  %br
  = @operative_plan.description
%hr
- @operative_plan.advances.each do |op|
  %b= op.name
  %br
  = raw op.description
  %hr

= link_to 'Editar', edit_operative_plan_path(@operative_plan)
\|
= link_to 'Atrás', operative_plans_path

app/views/payments/_form.html.haml
= form_for @payment do |f|
  .field
    = f.label :name, 'Nombre'
    = f.text_field :name
  .field
    = f.label :description, 'Descripción'
    = f.text_area :description
  .field
    = f.label :info, 'Documentos de soporte'
    = f.text_area :info
  .actions
    = f.submit 'Guardar'

app/views/payments/edit.html.haml
%h1 Editando pago

= render 'form'

= link_to 'Mostrar', @payment
\|
= link_to 'Atrás', payments_path

app/views/payments/index.html.haml
%h1 Mostrando pagos

- if current_user.admin?
  = link_to 'Nuevo pago', new_payment_path

%table
  %thead
    %tr
      %th Nombre
      %th Descripción
      %th Documentos de soporte
      %th
      %th
      %th

  %tbody
    - @payments.each do |payment|
      %tr
        %td= payment.name
        %td= payment.description
        %td= payment.info
        %td= link_to 'Mostrar', payment
        - if current_user.admin?
          %td= link_to 'Editar', edit_payment_path(payment)
          %td= link_to 'Eliminar', payment, method: :delete, data: { confirm: '¿Estás seguro?' }

%br

app/views/payments/new.html.haml
%h1 Nuevo pago

= render 'form'

= link_to 'Atrás', payments_path

app/views/payments/show.html.haml
%p
  %b Nombre:
  = @payment.name
%p
  %b Descripción:
  = @payment.description
%p
  %b Documentos de soporte:
  %br
  = raw @payment.info

= link_to 'Editar', edit_payment_path(@payment)
\|
= link_to 'Atrás', payments_path

app/views/welcome/index.html.haml
%h1 Bienvenidos
%p Este es un sitio web pensado para facilitar que los emprendedores accedan a la información que necesitan sobre distintos procesos, de una forma rápida y eficiente.
%p Para comenzar, inicia sesión. Si no tienes cuenta, regístrate.